version: '3'
services:
  jupyter:
    build: .
    volumes:
      - ../:/Users/Sampath/work
    ports:
      - 8888:8888
    container_name: jupyter_notebook
    command: "start-notebook.sh --NotebookApp.token="